site_url: https://branner.netlify.app/
logo_url: https://branner.netlify.app/icon.png

locale: 'de'

# publish_mode: editorial_workflow
backend:
  name: git-gateway
  branch: master
  squash_merges: true

# used together with `npx netlify-cms-proxy-server`. https://www.netlifycms.org/docs/beta-features/#working-with-a-local-git-repository
local_backend: true

media_folder: static/img
public_folder: /img

# Docs: https://www.netlifycms.org/docs/configuration-options/#collections
collections:
  - name: 'blog'
    label: 'Neuigkeiten'
    folder: 'content/blog'
    create: true
    format: 'frontmatter'
    slug: '{{fields.createdAt}}-{{slug}}'
    # summary: "{{fields.createdAt | date('YYYY-MM-DD')}}: {{fields.title}}"
    summary: '{{fields.createdAt}}: {{fields.title}}'
    sortable_fields: ['createdAt', 'title']
    view_filters:
      - label: 'Branner Group'
        field: 'section'
        pattern: 'Branner Group'
      - label: 'Fitness'
        field: 'section'
        pattern: 'Fitness'
      - label: 'Erdenwerk'
        field: 'section'
        pattern: 'Erdenwerk'
      - label: 'Entsorgung'
        field: 'section'
        pattern: 'Entsorgung'
      - label: 'Oberflächenbeh.'
        field: 'section'
        pattern: 'Oberflächenbeh.'
    fields:
      - { label: 'Sichtbar', name: 'visible', widget: 'boolean', default: false }
      - {
          label: 'Erstellt am',
          name: 'createdAt',
          widget: 'date',
          date_format: 'YYYY-MM-DD',
          format: 'YYYY-MM-DD',
          time_format: false,
        }
      - { label: 'Titel', name: 'title', widget: 'string', required: true }
      - { label: 'Beschreibung', name: 'description', widget: 'text', required: false }
      - {
          label: 'Bereich',
          name: 'section',
          widget: 'select',
          options: ['', 'Branner Group', 'Mobility', 'Fitness', 'Erdenwerk', 'Entsorgung', 'Oberflächenbeh.'],
          required: false,
        }
      - { label: 'Body', name: 'body', widget: 'markdown', required: false }
      - { label: 'SEO Titel', name: 'seo_title', widget: 'string', required: false }
      - { label: 'SEO Description', name: 'seo_description', widget: 'text', required: false }
  - name: 'jobs'
    label: 'Jobs'
    folder: 'content/jobs'
    create: true
    format: 'frontmatter'
    slug: '{{fields.createdAt}}-{{slug}}'
    summary: '{{fields.createdAt}}: {{fields.title}}'
    sortable_fields: ['createdAt', 'title']
    view_filters:
      - label: 'Branner Group'
        field: 'section'
        pattern: 'Branner Group'
      - label: 'Fitness'
        field: 'section'
        pattern: 'Fitness'
      - label: 'Erdenwerk'
        field: 'section'
        pattern: 'Erdenwerk'
      - label: 'Entsorgung'
        field: 'section'
        pattern: 'Entsorgung'
      - label: 'Oberflächenbeh.'
        field: 'section'
        pattern: 'Oberflächenbeh.'
    fields:
      - { label: 'Sichtbar', name: 'visible', widget: 'boolean', default: false }
      - { label: 'Erstellt am', name: 'createdAt', widget: 'datetime', date_format: 'YYYY-MM-DD', time_format: false }
      - { label: 'Titel', name: 'title', widget: 'string', required: true }
      - { label: 'Beschreibung', name: 'description', widget: 'text', required: false }
      - {
          label: 'Bereich',
          name: 'section',
          widget: 'select',
          options: ['', 'Branner Group', 'Mobility', 'Fitness', 'Erdenwerk', 'Entsorgung', 'Oberflächenbeh.'],
          required: false,
        }
      - { label: 'Body', name: 'body', widget: 'markdown', required: false }
      - { label: 'SEO Titel', name: 'seo_title', widget: 'string', required: false }
      - { label: 'SEO Description', name: 'seo_description', widget: 'text', required: false }

  - label: 'Seiten Info'
    name: 'site'
    files:
      - label: 'Info'
        name: 'info'
        file: 'content/site/info.json'
        format: 'json'
        editor:
          preview: false
        fields:
          - { label: Titel, name: sitename, widget: string, hint: 'Wird als Seitentitel genutzt' }
          - { label: Beschreibung, name: sitedescription, widget: string, hint: 'Beschreibung der Seite' }
          - {
              label: Sprache,
              name: sitelang,
              widget: string,
              pattern: ['^[a-z]{2}([-])?([A-Za-z]{2})?$', 'Must match "xx" or "xx-XX" syntax (ex. "en" or "sv-SE")'],
            }
          # - { label: Site Email, name: siteemail, widget: string, required: false }
